# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'If you are pre-releasing in beta, run `npm version prerelease --preid beta` beforehand.'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'server/.nvmrc'
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'server/.nvmrc'
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false
      - run: npm ci
      - run: npm publish --access public --tag ${{ inputs.tag }}
